Milestone: Create new component and complete the desing of calculator.
Arslan49sp/math-magicians pull request #2
Opened 2023-09-29 21:59 UTC by Arslan49sp

## This pull request contains the following features. 

- Remove previous boilerplate
- Create a `components` repository inside `src`
- Create a `Calculator.js` component and complete the design of the calculator. 
- Use at least one child component of the `Calculator.js`
- Use `Calculator.js` in the `App.js` component.

2023-09-30 01:27 UTC, skyv26 requested changes
## Hi @Arslan49sp , 

Good job so far 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## STATUS: REQUIRE CHANGES 🔴 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNjVhZjBiZjUzZmYxZjI1NGFhNGQ0ZjIyN2FhOTcwNDZlZmUzNmZkMiZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/L422JoNlBBBD42zkQ9/giphy.gif)

## Highlights
- Good **PR** title ✅ 
- Descriptive *PR* description ✅ 
- Implement the features ✅ 
- Professional `README` template ✅ 
- Meaningful **Github** commits ✅ 

## Required Changes ♻️

- [ ] As per the requirement. you should delete all the boilerplate code, but you still have the `App.test.js`, `webVitals`, and `setupTest` files, in your project that need to be deleted, which comes pre-defined with the CRA template. Later on, you will learn how to add them all back with a purpose.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

#### Cheers, and Happy coding!👏👏👏

## ⚠️  WARNING ⚠️ 
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

## Have any doubt ❓ 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @skyv26 in your question so I can receive the notification. You can also follow me on the below platforms

<table>
<tr>
<td>

<a href="https://github.com/skyv26">
   <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" alt="@skyv26" />
</a>

</td>
<td>

<a href="https://www.linkedin.com/in/skyv2022/">
   <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="linkedin-skyv2022" />
</a>

</td>
<td>

<a href="https://twitter.com/vrma_aakash">
   <img src="https://img.shields.io/badge/Twitter-1DA1F2?style=for-the-badge&logo=twitter&logoColor=white" alt="@vrma_aakash" />
</a>

</td>
<td>

<a href="https://www.instagram.com/skybrel/">
   <img src="https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white" alt="@skybrel" />
</a>

</td>
<td>

<a href="https://www.frontendmentor.io/profile/skyv26">
   <img src="https://user-images.githubusercontent.com/66476329/243158690-61eb1021-fbb6-464d-b841-a09c4caa156e.png" alt="@skybrel" />
</a>

</td>
</tr>
</table>

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 01:27 UTC, skyv26 commented on src/components/Calculator.js
- [ ] Please 🙏🏻 adhere to the project requirement, according to which your design should match with provided `wireframe`. No doubt you did an awesome job, but following the requirements at the detail level is very important. Kindly fix the colours, and make your design look big and centre on the screen.

### Requirement
![image](https://github.com/Arslan49sp/math-magicians/assets/66476329/a22e6c0a-1bcc-42e4-94a9-d7325568a84f)

### Design Comparison
<table>
<tr>
<th>Wireframe Design</th>
<th>Your Design</th>
</tr>
<tr>
<td>

![Screenshot from 2023-09-30 06-45-41](https://github.com/Arslan49sp/math-magicians/assets/66476329/50e44361-da62-4c9d-8c8b-cb2bb5707657)

</td>
<td>

![Screenshot from 2023-09-30 06-45-23](https://github.com/Arslan49sp/math-magicians/assets/66476329/5deef3a7-e4f8-48e1-b92e-5a1059dbfbff)

</td>
</tr>
</table>

2023-09-30 01:27 UTC, skyv26 commented on src/components/Calculator.js
> +        return <InputButton inputSymbol={n} key={n} background="gray" />;
- [ ] Kindly make sure that your application is running without any kind of warning or errors, I noticed that your project have some issue that needs to be addressed before moving further. Please take a look at the below errors and try to solve it, debugging your code will help you to be a more better developer.

![image](https://github.com/Arslan49sp/math-magicians/assets/66476329/bac5d656-610a-4d82-9051-76d8455eca46)

2023-09-30 08:36 UTC, Johnadibe approved these changes
# Status: Approved ✔️
### Hi @Arslan49sp👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![LeonardoInGatsby](https://user-images.githubusercontent.com/38088818/233992044-ad00b20f-3f2f-4c86-8b94-1e613432af5f.gif)

## Highlights
- Implemented all changes requested by the code reviewer✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 08:41 UTC, merged

2023-10-25 22:45 UTC, AbayomiOlaoye reviewed
## STATUS: APPROVED :green_circle:  

Hi @Arslan49sp    :wave: :wave:, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![applause](https://user-images.githubusercontent.com/99715640/213818870-485b6c36-1d87-4b93-9a0c-ce2ae86d9a9d.gif)

## Highlights
- Cleanly written code :white_check_mark: 
- File structure as recommended ✅ 
- Nicely implemented functionalities ✅ 
- Good use of Gitflow ✅ 
- No linter issues :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._