Milestone: Make the calculator functional.
Arslan49sp/math-magicians pull request #3
Opened 2023-09-30 02:25 UTC by Arslan49sp

## This pull request contains the following features 

- add `calculate.js` and `operate.js` files in the `logic` directory. 
- import it in `Calculator.js` and implement functionality. 
- Use event handlers.

2023-09-30 09:20 UTC, Ibizugbe requested changes
Hi @Arslan49sp 👋🏼👋🏼👋🏼, 

![require_changes](https://github.com/Arslan49sp/math-magicians/assets/64643995/fddf7b0e-0e5c-4de4-a0d6-7e3e86063e7a)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are correctly setup and they are passing👍🏼.
- [x] The calculator uses `useState` to handle state👍🏼.
- [x] Props are correctly passed to child components👍🏼.
- [x] gitflow is used👍🏼.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 09:20 UTC, Ibizugbe commented on src/logic/calculate.js
> +  // }
Nice job so far, every thing looks good😉. Just a little issue, kindly take away every commented piece or block of code from your project as it makes your codebase look messy and gives it a less professional look😉.

2023-09-30 11:50 UTC, FrederickMih approved these changes
## Hi :raising_hand: :raising_hand: @Arslan49sp , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

:tada: :champagne: <img src="https://media.giphy.com/media/LtkRsMZNSChvICUFhV/giphy.gif"  width ="160"><img> :tada: :champagne: 

## Highlights :green_circle: 

- Commented codes removed :+1: 

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-30 18:03 UTC, merged

2023-10-25 22:46 UTC, Lucas-Masaba reviewed
# Hello @Arslan49sp  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![almost-there](https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)

## Highlights 🍾 
- Project works as expected :gear: 

## Optional suggestions 💭 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._